"""Add transfer_type on transfers

Revision ID: 44602dd22fbb
Revises: eb42ea3f72e6
Create Date: 2026-08-24 20:04:46.243893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44602dd22fbb'
down_revision = 'eb42ea3f72e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_type', sa.Enum('deposit', 'withdraw', name='transfertype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('transfer_type')

    # ### end Alembic commands ###
