"""Add transfer_type on transfers

Revision ID: 44602dd22fbb
Revises: eb42ea3f72e6
Create Date: 2026-08-24 20:04:46.243893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44602dd22fbb'
down_revision = 'eb42ea3f72e6'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Cria o tipo ENUM manualmente no Postgres antes de usar na tabela
    transfer_type_enum = sa.Enum('deposit', 'withdraw', name='transfertype')
    transfer_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_type', transfer_type_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('transfer_type')

    # 1. Cria o tipo ENUM manualmente no Postgres antes de usar na tabela
    transfer_type_enum = sa.Enum('deposit', 'withdraw', name='transfertype')
    transfer_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
