"""Add role name unique constraint.

Revision ID: b4cb5924e483
Revises: 4ca777f60c83
Create Date: 2026-08-04 16:39:58.356470

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b4cb5924e483'
down_revision = '4ca777f60c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    # ### end Alembic commands ###
