"""Add description on transfers

Revision ID: eb42ea3f72e6
Revises: f43ed6483aec
Create Date: 2026-08-24 19:35:38.729877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb42ea3f72e6'
down_revision = 'f43ed6483aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
